backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "static/data/blogposts"
    create: true
    fields:
    - { label: "Show on index", name: "showonindex", widget: "boolean", default: true }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Date", name: "date", widget: "string" }
    - { label: "Stamp (for sorting)", name: "datestamp", widget: "date", format: "MM.YYYY" }
    - { label: "Read Time", name: "readtime", widget: "string" }
    - { label: "Slug", name: "slug", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
  - name: "garden"
    label: "Garden"
    folder: "static/data/garden"
    create: true
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "URL", name: "url", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
  - name: "projects"
    label: "Projects"
    folder: "static/data/projects"
    create: true
    fields:
    - { label: "Show on index", name: "showonindex", widget: "boolean", default: true }
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Cover", name: "cover", widget: "image" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Date", name: "date", widget: "string" }
    - { label: "Stamp (for sorting)", name: "datestamp", widget: "date", format: "MM.YYYY" }
    - { label: "Type", name: "type", widget: "string" }
    - { label: "Documentation available?", name: "documentationAvailable", widget: "boolean", default: false }
    - { label: "Link1", name: "link1", widget: "string", required: false }
    - { label: "URL1", name: "url1", widget: "string", required: false }
    - { label: "Link2", name: "link2", widget: "string", required: false }
    - { label: "URL2", name: "url2", widget: "string", required: false }
    - { label: "Link3", name: "link3", widget: "string", required: false }
    - { label: "URL3", name: "url3", widget: "string", required: false }
    - { label: "Slug", name: "slug", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
  - name: "socialservice"
    label: "Social Service"
    folder: "static/data/socialservice"
    create: true
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "string" }
    - { label: "Stamp (for sorting)", name: "datestamp", widget: "date", format: "MM.YYYY" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Link1", name: "link1", widget: "string", required: false }
    - { label: "URL1", name: "url1", widget: "string", required: false }
    - { label: "Link2", name: "link2", widget: "string", required: false }
    - { label: "URL2", name: "url2", widget: "string", required: false }
  - name: "dubs"
    label: "Victories and Participations"
    folder: "static/data/dubs"
    create: true
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "string" }
    - { label: "Stamp (for sorting)", name: "datestamp", widget: "date", format: "MM.YYYY" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Link1", name: "link1", widget: "string", required: false }
    - { label: "URL1", name: "url1", widget: "string", required: false }
    - { label: "Link2", name: "link2", widget: "string", required: false }
    - { label: "URL2", name: "url2", widget: "string", required: false }
  - name: "leadership"
    label: "Leadership"
    folder: "static/data/leadership"
    create: true
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "string" }
    - { label: "Stamp (for sorting)", name: "datestamp", widget: "date", format: "MM.YYYY" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Link1", name: "link1", widget: "string", required: false }
    - { label: "URL1", name: "url1", widget: "string", required: false }
    - { label: "Link2", name: "link2", widget: "string", required: false }
    - { label: "URL2", name: "url2", widget: "string", required: false }