name: Garden Plants Fetch Workflow

on:
  # push: # Disabled because this creates a perpetual loop, every action causes a push which triggers the actions again
  #   branches:
  #     - main
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Garden Plants from Notion
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://api.notion.com/v1/databases/1e6d541ec3974208a619db7c83552cc9/query
          CONFIGURATION: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.NOTION_TOKEN }}", "Accept": "application/json", "Notion-Version": "2022-02-22" } }'
          SAVE_LOCATION: static/data
          SAVE_NAME: plants

      - name: Update plants.json
        uses: test-room-7/action-update-file@v1
        with:
          file-path: static/data/plants.json
          commit-msg: Updated plants.json
          github-token: ${{ secrets.TOKEN }}
