name: Fetch API

on:
  push:
    branches:
      - main
  # schedule:
    # - cron: "*/5 * * * *"

jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: https://potion-api.vercel.app/table?id=fe3fe0e8c9e54061b7412307da4c035f
          SAVE_LOCATION: data
          SAVE_NAME: socials

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: data/socials.json
          commit-msg: Updated socials.json 
          github-token: ${{ secrets.TOKEN }}